### ISSUE TITLE
Current ktfmt version doesn't work with Gradle 7.2

### ISSUE THREAD

**Issue by rsookram** [cortinico/ktfmt-gradle#37]
## 🐛 Describe the bug
After updating [a project](https://github.com/rsookram/srs/) using ktfmt-gradle to Gradle 7.2, ktfmt-gradle fails to process files. The error message looks like :point_down:  (repeated for each file that needs to be processed):

```
[ktfmt] Failed to analyse: /home/me/src/srs/app/src/main/java/io/github/rsookram/srs/App.kt
[ktfmt] e: Generic error during file processing
```

The error message isn't too helpful, but upon further debugging, the code is falling into [this path](https://github.com/cortinico/ktfmt-gradle/blob/7521ad34601fad195f66a2f651271c5940b2f247/plugin-build/plugin/src/main/java/com/ncorti/ktfmt/gradle/tasks/KtfmtBaseTask.kt#L112) and the actual `Exception` is:

```
java.lang.RuntimeException: Unsupported runtime Kotlin version: 1.5.21
        at com.facebook.ktfmt.FormatterKt.createAstVisitor(Formatter.kt:160)
        at com.facebook.ktfmt.FormatterKt.prettyPrint(Formatter.kt:136)
        at com.facebook.ktfmt.FormatterKt.format(Formatter.kt:124)
        at com.ncorti.ktfmt.gradle.tasks.KtfmtBaseTask.processFile$plugin(KtfmtBaseTask.kt:103)
        at com.ncorti.ktfmt.gradle.tasks.KtfmtBaseTask$processFileCollection$$inlined$map$lambda$1.invokeSuspend(KtfmtBaseTask.kt:122)
        at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
        at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
        at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:571)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:678)
        at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:665)
```

This seems to be because ktfmt-gradle is [using ktfmt version 0.24](https://github.com/cortinico/ktfmt-gradle/blob/7521ad34601fad195f66a2f651271c5940b2f247/plugin-build/buildSrc/src/main/java/Dependencies.kt#L6), but Kotlin 1.5 isn't supported until [ktfmt 0.25](https://github.com/facebookincubator/ktfmt/releases/tag/v0.25).

It happens when upgrading to Gradle 7.2 because Gradle [updated its version of Kotlin to 1.5.21](https://docs.gradle.org/current/userguide/upgrading_version_7.html#updates_to_bundled_gradle_dependencies) in that version.

## ✅ Expected behavior
I expected ktfmt-gradle to continue to process files like before the Gradle update.

## 💣 Steps to reproduce
Run either the `ktfmtFormat` or `ktfmtCheck` task on a project using Gradle 7.2.

I was also able to reproduce the issue by cloning the ktfmt-gradle repo, updating to Gradle 7.2, then running the tests with `./gradlew test`.

## :wrench: Steps to fix?
Updating ktfmt to 0.25 or newer seems to work for me. In my local clone of ktfmt-gradle, I was able to update Gradle to 7.2 and ktfmt to 0.25 (0.27 is fine too), and the tests passed. I can put up a PR with these changes if it sounds reasonable. I'm not sure if there's a reason for sticking with an older ktfmt version though.

## 📱 Tech info
 - OS: Linux
 - Library version: 0.6.0 (although it also happens at the HEAD of `master`: https://github.com/cortinico/ktfmt-gradle/commit/7521ad34601fad195f66a2f651271c5940b2f247)

**Comment by cortinico** [comment]
Version `0.7.0` should solve this 👍 Let me know if it does now
